### ISSUE TITLE
Знайти фото Лесі Українки в інтернеті

### ISSUE THREAD

**Issue by roksik4** [roksik4/pr4#1]
Знайти найкраще фото в інтернеті

**Comment by roksik2** [comment]
Вже шукаю

**Comment by roksik2** [comment]
![049A0C7B-929C-4228-8DB2-2B88757B365B](https://user-images.githubusercontent.com/116970119/198846281-6fac2d5a-79d4-4d72-89cc-53d80cb3b4f1.jpeg)

**Comment by roksik2** [comment]
Зображення знайдено
